apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: argahv/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
    - image: argahv/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
    - image: argahv/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
deploy:
  kubectl:
    manifests:
      - "k8s/*"
